#!/usr/bin/env bash
set -euo pipefail

WORK=${WORK:-/root/rivermind-data/qwen_ag_lm}
cd "$WORK"
. "$WORK/env.sh" 2>/dev/null || true
. "$WORK/venv/bin/activate" 2>/dev/null || true

SCRIPT_DIR=${SCRIPT_DIR:-scripts}
PIPELINE_DIR=${PIPELINE_DIR:-data/synth_cpt_1m_pruned_v2}
POSTRUN_TAG=${POSTRUN_TAG:-postv12_solvedbiased_hybrid_v44per_problem_focus_v1}
QUEUE_LOG=${QUEUE_LOG:-outputs/${POSTRUN_TAG}.queue_after_existing.log}
WAIT_INTERVAL=${WAIT_INTERVAL:-60}
DRY_RUN=${DRY_RUN:-0}

BLOCKING_PATTERN=${BLOCKING_PATTERN:-/tmp/qwen_ag_scripts_c541dd4|/tmp/qwen_ag_scripts_postv12_adaptive_progress_coverage_v1|run_qwen_ag_benchmark.py|train_qwen_aux_lora.py}
REFERENCE_OUT_DIR=${REFERENCE_OUT_DIR:-outputs/final_eval_imo_ag30_qwen_unsolved_factctx_promptaug_top8_candidate_signal_postrun_value_v12_default_v1_depth48_t240_w150_nrs48_qm3_sigrep4_blinedia_statededup_nodediv_dsltpl_combotpl_rarecombo_vprior_v1}
MINE_STATIC_PROGRESS_TYPE_BONUS=${MINE_STATIC_PROGRESS_TYPE_BONUS:-1}
STATIC_PROGRESS_TYPE_BONUS_JSON=${STATIC_PROGRESS_TYPE_BONUS_JSON:-outputs/candidate_static_progress_type_bonus_${POSTRUN_TAG}.json}
STATIC_PROGRESS_TYPE_BONUS_MIN_DELTA=${STATIC_PROGRESS_TYPE_BONUS_MIN_DELTA:-70}
STATIC_PROGRESS_TYPE_BONUS_MIN_DELTA_FLOOR=${STATIC_PROGRESS_TYPE_BONUS_MIN_DELTA_FLOOR:-25}
STATIC_PROGRESS_TYPE_BONUS_MIN_ROOT_RATIO=${STATIC_PROGRESS_TYPE_BONUS_MIN_ROOT_RATIO:-0.6}
STATIC_PROGRESS_TYPE_BONUS_TOPN=${STATIC_PROGRESS_TYPE_BONUS_TOPN:-48}
STATIC_PROGRESS_TYPE_BONUS_PER_PROBLEM_TOPN=${STATIC_PROGRESS_TYPE_BONUS_PER_PROBLEM_TOPN:-12}
STATIC_PROGRESS_TYPE_BONUS_PER_PROBLEM_UPLIFT=${STATIC_PROGRESS_TYPE_BONUS_PER_PROBLEM_UPLIFT:-0.45}
STATIC_PROGRESS_TYPE_BONUS_PER_PROBLEM_MAX=${STATIC_PROGRESS_TYPE_BONUS_PER_PROBLEM_MAX:-3.2}
STATIC_PROGRESS_TYPE_BONUS_BASE=${STATIC_PROGRESS_TYPE_BONUS_BASE:-1.2}
STATIC_PROGRESS_TYPE_BONUS_DELTA_WEIGHT=${STATIC_PROGRESS_TYPE_BONUS_DELTA_WEIGHT:-0.55}
STATIC_PROGRESS_TYPE_BONUS_REPEAT_WEIGHT=${STATIC_PROGRESS_TYPE_BONUS_REPEAT_WEIGHT:-0.08}
STATIC_PROGRESS_TYPE_BONUS_REPEAT_CAP=${STATIC_PROGRESS_TYPE_BONUS_REPEAT_CAP:-0.25}
STATIC_PROGRESS_TYPE_BONUS_RATIO_WEIGHT=${STATIC_PROGRESS_TYPE_BONUS_RATIO_WEIGHT:-0.18}
STATIC_PROGRESS_TYPE_BONUS_RATIO_CAP=${STATIC_PROGRESS_TYPE_BONUS_RATIO_CAP:-0.35}
STATIC_PROGRESS_TYPE_BONUS_SOLVED_BONUS=${STATIC_PROGRESS_TYPE_BONUS_SOLVED_BONUS:-0.55}
STATIC_PROGRESS_TYPE_BONUS_MAX=${STATIC_PROGRESS_TYPE_BONUS_MAX:-2.8}
SCOUT_CANDIDATE_DEPTH_TAIL_EVAL_SLOTS=${SCOUT_CANDIDATE_DEPTH_TAIL_EVAL_SLOTS:-4}
SCOUT_CANDIDATE_DEPTH_TAIL_EVAL_STRATEGY=${SCOUT_CANDIDATE_DEPTH_TAIL_EVAL_STRATEGY:-near_spread}
CLEAN_CANDIDATE_DEPTH_EVAL_LIMIT=${CLEAN_CANDIDATE_DEPTH_EVAL_LIMIT:-48}
CLEAN_CANDIDATE_DEPTH_TAIL_EVAL_SLOTS=${CLEAN_CANDIDATE_DEPTH_TAIL_EVAL_SLOTS:-4}
CLEAN_CANDIDATE_DEPTH_TAIL_EVAL_STRATEGY=${CLEAN_CANDIDATE_DEPTH_TAIL_EVAL_STRATEGY:-near_spread}
SCOUT_CANDIDATE_ADAPTIVE_TYPE_PENALTY=${SCOUT_CANDIDATE_ADAPTIVE_TYPE_PENALTY:-1}
CLEAN_CANDIDATE_ADAPTIVE_TYPE_PENALTY=${CLEAN_CANDIDATE_ADAPTIVE_TYPE_PENALTY:-1}
CANDIDATE_ADAPTIVE_TYPE_PENALTY_THRESHOLD=${CANDIDATE_ADAPTIVE_TYPE_PENALTY_THRESHOLD:-32}
CANDIDATE_ADAPTIVE_TYPE_PENALTY_WEIGHT=${CANDIDATE_ADAPTIVE_TYPE_PENALTY_WEIGHT:-0.35}
CANDIDATE_ADAPTIVE_TYPE_PENALTY_MAX=${CANDIDATE_ADAPTIVE_TYPE_PENALTY_MAX:-1.5}
CANDIDATE_ADAPTIVE_TYPE_PENALTY_REASONS=${CANDIDATE_ADAPTIVE_TYPE_PENALTY_REASONS:-point_too_close,point_too_far,point_already_exists,unknown_point}
CANDIDATE_DYNAMIC_PROGRESS_TYPE_ANCHOR=${CANDIDATE_DYNAMIC_PROGRESS_TYPE_ANCHOR:-1}
CANDIDATE_DYNAMIC_PROGRESS_TYPE_MIN_DELTA=${CANDIDATE_DYNAMIC_PROGRESS_TYPE_MIN_DELTA:-60}
CANDIDATE_DYNAMIC_PROGRESS_TYPE_MIN_DELTA_FLOOR=${CANDIDATE_DYNAMIC_PROGRESS_TYPE_MIN_DELTA_FLOOR:-25}
CANDIDATE_DYNAMIC_PROGRESS_TYPE_MIN_ROOT_RATIO=${CANDIDATE_DYNAMIC_PROGRESS_TYPE_MIN_ROOT_RATIO:-0.6}
CANDIDATE_DYNAMIC_PROGRESS_TYPE_BONUS_BASE=${CANDIDATE_DYNAMIC_PROGRESS_TYPE_BONUS_BASE:-2.0}
CANDIDATE_DYNAMIC_PROGRESS_TYPE_BONUS_WEIGHT=${CANDIDATE_DYNAMIC_PROGRESS_TYPE_BONUS_WEIGHT:-0.08}
CANDIDATE_DYNAMIC_PROGRESS_TYPE_BONUS_MAX=${CANDIDATE_DYNAMIC_PROGRESS_TYPE_BONUS_MAX:-3.2}
TRAIN_SCOUT_VALUE_MODEL=${TRAIN_SCOUT_VALUE_MODEL:-1}
SCOUT_REFRESH_VALUE_ROLE=${SCOUT_REFRESH_VALUE_ROLE:-secondary}
SCOUT_VALUE_DISABLE_PROGRESS_POSITIVES=${SCOUT_VALUE_DISABLE_PROGRESS_POSITIVES:-1}
SCOUT_VALUE_TAG=${SCOUT_VALUE_TAG:-v44per_problem_focus_pairwise_currentref_solvedonly_timeoutfb4_secondary_v1}
CLEAN_SECONDARY_VALUE_MODEL=${CLEAN_SECONDARY_VALUE_MODEL:-outputs/candidate_value_model_${SCOUT_VALUE_TAG}/candidate_value_model.json}

mkdir -p "$(dirname "$QUEUE_LOG")"

log() {
  date '+%F %T %z' | tr -d '\n' | tee -a "$QUEUE_LOG"
  printf ' %s\n' "$*" | tee -a "$QUEUE_LOG"
}

process_active() {
  python - "$BLOCKING_PATTERN" <<'PY'
import os
import re
import subprocess
import sys

pattern = sys.argv[1]
self_pid = os.getpid()
parent_pid = os.getppid()
try:
    regex = re.compile(pattern)
except re.error:
    regex = re.compile(re.escape(pattern))

for line in subprocess.check_output(['ps', '-eo', 'pid=,ppid=,args='], text=True).splitlines():
    line = line.strip()
    if not line:
        continue
    parts = line.split(maxsplit=2)
    if len(parts) < 3:
        continue
    pid_text, ppid_text, args = parts
    try:
        pid = int(pid_text)
        ppid = int(ppid_text)
    except ValueError:
        continue
    if pid in {self_pid, parent_pid} or ppid in {self_pid, parent_pid}:
        continue
    if 'queue_v22tail_after_existing_qwen_pipelines.sh' in args:
        continue
    if regex.search(args):
        print(line)
        sys.exit(0)
sys.exit(1)
PY
}

log "queue v44per_problem_focus after existing Qwen pipelines"
log "blocking pattern: $BLOCKING_PATTERN"
while process_active >> "$QUEUE_LOG" 2>&1; do
  log "blocking Qwen pipeline still active; sleeping ${WAIT_INTERVAL}s"
  sleep "$WAIT_INTERVAL"
done

log "no blocking Qwen pipeline active; launching v44per_problem_focus scout and hybrid wrapper"
log "tail slots: scout=${SCOUT_CANDIDATE_DEPTH_TAIL_EVAL_SLOTS}/${SCOUT_CANDIDATE_DEPTH_TAIL_EVAL_STRATEGY}; clean=${CLEAN_CANDIDATE_DEPTH_TAIL_EVAL_SLOTS}/${CLEAN_CANDIDATE_DEPTH_TAIL_EVAL_STRATEGY}; clean_depth_eval=${CLEAN_CANDIDATE_DEPTH_EVAL_LIMIT}"
log "adaptive type penalty: scout=${SCOUT_CANDIDATE_ADAPTIVE_TYPE_PENALTY}; clean=${CLEAN_CANDIDATE_ADAPTIVE_TYPE_PENALTY}; threshold=${CANDIDATE_ADAPTIVE_TYPE_PENALTY_THRESHOLD}; weight=${CANDIDATE_ADAPTIVE_TYPE_PENALTY_WEIGHT}; max=${CANDIDATE_ADAPTIVE_TYPE_PENALTY_MAX}; reasons=${CANDIDATE_ADAPTIVE_TYPE_PENALTY_REASONS}"
log "dynamic progress type anchor: enabled=${CANDIDATE_DYNAMIC_PROGRESS_TYPE_ANCHOR}; min_delta=${CANDIDATE_DYNAMIC_PROGRESS_TYPE_MIN_DELTA}; floor=${CANDIDATE_DYNAMIC_PROGRESS_TYPE_MIN_DELTA_FLOOR}; ratio=${CANDIDATE_DYNAMIC_PROGRESS_TYPE_MIN_ROOT_RATIO}; base=${CANDIDATE_DYNAMIC_PROGRESS_TYPE_BONUS_BASE}; weight=${CANDIDATE_DYNAMIC_PROGRESS_TYPE_BONUS_WEIGHT}; max=${CANDIDATE_DYNAMIC_PROGRESS_TYPE_BONUS_MAX}"
log "scout value refresh: train=${TRAIN_SCOUT_VALUE_MODEL}; role=${SCOUT_REFRESH_VALUE_ROLE}; solved_only_progress_disabled=${SCOUT_VALUE_DISABLE_PROGRESS_POSITIVES}; tag=${SCOUT_VALUE_TAG}"
log "hybrid secondary value model: ${CLEAN_SECONDARY_VALUE_MODEL}"

if [ "$DRY_RUN" = "1" ]; then
  log "dry run enabled; not launching"
  exit 0
fi

CANDIDATE_STATIC_PROGRESS_TYPE_BONUS=${CANDIDATE_STATIC_PROGRESS_TYPE_BONUS:-}
if [ "$MINE_STATIC_PROGRESS_TYPE_BONUS" = "1" ]; then
  if [ ! -d "$REFERENCE_OUT_DIR/events" ]; then
    log "missing reference events dir for static progress mining: $REFERENCE_OUT_DIR/events"
    exit 1
  fi
  log "mining static progress type bonus: out=${STATIC_PROGRESS_TYPE_BONUS_JSON}; min_delta=${STATIC_PROGRESS_TYPE_BONUS_MIN_DELTA}; floor=${STATIC_PROGRESS_TYPE_BONUS_MIN_DELTA_FLOOR}; ratio=${STATIC_PROGRESS_TYPE_BONUS_MIN_ROOT_RATIO}; topn=${STATIC_PROGRESS_TYPE_BONUS_TOPN}; per_problem_topn=${STATIC_PROGRESS_TYPE_BONUS_PER_PROBLEM_TOPN}; per_problem_uplift=${STATIC_PROGRESS_TYPE_BONUS_PER_PROBLEM_UPLIFT}; per_problem_max=${STATIC_PROGRESS_TYPE_BONUS_PER_PROBLEM_MAX}; base=${STATIC_PROGRESS_TYPE_BONUS_BASE}; delta_weight=${STATIC_PROGRESS_TYPE_BONUS_DELTA_WEIGHT}; repeat_weight=${STATIC_PROGRESS_TYPE_BONUS_REPEAT_WEIGHT}; repeat_cap=${STATIC_PROGRESS_TYPE_BONUS_REPEAT_CAP}; ratio_weight=${STATIC_PROGRESS_TYPE_BONUS_RATIO_WEIGHT}; ratio_cap=${STATIC_PROGRESS_TYPE_BONUS_RATIO_CAP}; solved=${STATIC_PROGRESS_TYPE_BONUS_SOLVED_BONUS}; max=${STATIC_PROGRESS_TYPE_BONUS_MAX}"
  python "$SCRIPT_DIR/mine_candidate_progress_type_bonus.py" \
    --events_dir "$REFERENCE_OUT_DIR/events" \
    --out "$STATIC_PROGRESS_TYPE_BONUS_JSON" \
    --min_delta "$STATIC_PROGRESS_TYPE_BONUS_MIN_DELTA" \
    --min_delta_floor "$STATIC_PROGRESS_TYPE_BONUS_MIN_DELTA_FLOOR" \
    --min_root_ratio "$STATIC_PROGRESS_TYPE_BONUS_MIN_ROOT_RATIO" \
    --topn "$STATIC_PROGRESS_TYPE_BONUS_TOPN" \
    --per_problem_topn "$STATIC_PROGRESS_TYPE_BONUS_PER_PROBLEM_TOPN" \
    --per_problem_bonus_uplift "$STATIC_PROGRESS_TYPE_BONUS_PER_PROBLEM_UPLIFT" \
    --per_problem_max_bonus "$STATIC_PROGRESS_TYPE_BONUS_PER_PROBLEM_MAX" \
    --base_bonus "$STATIC_PROGRESS_TYPE_BONUS_BASE" \
    --delta_weight "$STATIC_PROGRESS_TYPE_BONUS_DELTA_WEIGHT" \
    --repeat_weight "$STATIC_PROGRESS_TYPE_BONUS_REPEAT_WEIGHT" \
    --repeat_bonus_cap "$STATIC_PROGRESS_TYPE_BONUS_REPEAT_CAP" \
    --ratio_weight "$STATIC_PROGRESS_TYPE_BONUS_RATIO_WEIGHT" \
    --ratio_bonus_cap "$STATIC_PROGRESS_TYPE_BONUS_RATIO_CAP" \
    --solved_bonus "$STATIC_PROGRESS_TYPE_BONUS_SOLVED_BONUS" \
    --max_bonus "$STATIC_PROGRESS_TYPE_BONUS_MAX" \
    >> "$QUEUE_LOG" 2>&1
  CANDIDATE_STATIC_PROGRESS_TYPE_BONUS="$STATIC_PROGRESS_TYPE_BONUS_JSON"
fi
log "static progress type bonus: ${CANDIDATE_STATIC_PROGRESS_TYPE_BONUS:-none}"

SCOUT_LAUNCH_LOG=${SCOUT_LAUNCH_LOG:-outputs/${POSTRUN_TAG}.scout.launch.log}
HYBRID_LAUNCH_LOG=${HYBRID_LAUNCH_LOG:-outputs/${POSTRUN_TAG}.hybrid.launch.log}

env \
  SCRIPT_DIR="$SCRIPT_DIR" \
  SCOUT_CANDIDATE_DEPTH_TAIL_EVAL_SLOTS="$SCOUT_CANDIDATE_DEPTH_TAIL_EVAL_SLOTS" \
  SCOUT_CANDIDATE_DEPTH_TAIL_EVAL_STRATEGY="$SCOUT_CANDIDATE_DEPTH_TAIL_EVAL_STRATEGY" \
  SCOUT_CANDIDATE_ADAPTIVE_TYPE_PENALTY="$SCOUT_CANDIDATE_ADAPTIVE_TYPE_PENALTY" \
  SCOUT_CANDIDATE_ADAPTIVE_TYPE_PENALTY_THRESHOLD="$CANDIDATE_ADAPTIVE_TYPE_PENALTY_THRESHOLD" \
  SCOUT_CANDIDATE_ADAPTIVE_TYPE_PENALTY_WEIGHT="$CANDIDATE_ADAPTIVE_TYPE_PENALTY_WEIGHT" \
  SCOUT_CANDIDATE_ADAPTIVE_TYPE_PENALTY_MAX="$CANDIDATE_ADAPTIVE_TYPE_PENALTY_MAX" \
  SCOUT_CANDIDATE_ADAPTIVE_TYPE_PENALTY_REASONS="$CANDIDATE_ADAPTIVE_TYPE_PENALTY_REASONS" \
  SCOUT_CANDIDATE_DYNAMIC_PROGRESS_TYPE_ANCHOR="$CANDIDATE_DYNAMIC_PROGRESS_TYPE_ANCHOR" \
  SCOUT_CANDIDATE_DYNAMIC_PROGRESS_TYPE_MIN_DELTA="$CANDIDATE_DYNAMIC_PROGRESS_TYPE_MIN_DELTA" \
  SCOUT_CANDIDATE_DYNAMIC_PROGRESS_TYPE_MIN_DELTA_FLOOR="$CANDIDATE_DYNAMIC_PROGRESS_TYPE_MIN_DELTA_FLOOR" \
  SCOUT_CANDIDATE_DYNAMIC_PROGRESS_TYPE_MIN_ROOT_RATIO="$CANDIDATE_DYNAMIC_PROGRESS_TYPE_MIN_ROOT_RATIO" \
  SCOUT_CANDIDATE_DYNAMIC_PROGRESS_TYPE_BONUS_BASE="$CANDIDATE_DYNAMIC_PROGRESS_TYPE_BONUS_BASE" \
  SCOUT_CANDIDATE_DYNAMIC_PROGRESS_TYPE_BONUS_WEIGHT="$CANDIDATE_DYNAMIC_PROGRESS_TYPE_BONUS_WEIGHT" \
  SCOUT_CANDIDATE_DYNAMIC_PROGRESS_TYPE_BONUS_MAX="$CANDIDATE_DYNAMIC_PROGRESS_TYPE_BONUS_MAX" \
  SCOUT_CANDIDATE_STATIC_PROGRESS_TYPE_BONUS="$CANDIDATE_STATIC_PROGRESS_TYPE_BONUS" \
  TRAIN_SCOUT_VALUE_MODEL="$TRAIN_SCOUT_VALUE_MODEL" \
  SCOUT_REFRESH_VALUE_ROLE="$SCOUT_REFRESH_VALUE_ROLE" \
  SCOUT_VALUE_DISABLE_PROGRESS_POSITIVES="$SCOUT_VALUE_DISABLE_PROGRESS_POSITIVES" \
  SCOUT_VALUE_TAG="$SCOUT_VALUE_TAG" \
  nohup bash "$PIPELINE_DIR/run_pairwise_scout_after_clean_wait.sh" \
  > "$SCOUT_LAUNCH_LOG" 2>&1 < /dev/null &
SCOUT_PID=$!

env \
  SCRIPT_DIR="$SCRIPT_DIR" \
  POSTRUN_TAG="$POSTRUN_TAG" \
  QUEUE_LOG="outputs/${POSTRUN_TAG}.hybrid.queue.log" \
  WAIT_FOR_SCOUT=1 \
  SCOUT_CANDIDATE_DEPTH_TAIL_EVAL_SLOTS="$SCOUT_CANDIDATE_DEPTH_TAIL_EVAL_SLOTS" \
  SCOUT_CANDIDATE_DEPTH_TAIL_EVAL_STRATEGY="$SCOUT_CANDIDATE_DEPTH_TAIL_EVAL_STRATEGY" \
  CLEAN_CANDIDATE_DEPTH_EVAL_LIMIT="$CLEAN_CANDIDATE_DEPTH_EVAL_LIMIT" \
  CLEAN_CANDIDATE_DEPTH_TAIL_EVAL_SLOTS="$CLEAN_CANDIDATE_DEPTH_TAIL_EVAL_SLOTS" \
  CLEAN_CANDIDATE_DEPTH_TAIL_EVAL_STRATEGY="$CLEAN_CANDIDATE_DEPTH_TAIL_EVAL_STRATEGY" \
  CLEAN_CANDIDATE_ADAPTIVE_TYPE_PENALTY="$CLEAN_CANDIDATE_ADAPTIVE_TYPE_PENALTY" \
  CLEAN_CANDIDATE_ADAPTIVE_TYPE_PENALTY_THRESHOLD="$CANDIDATE_ADAPTIVE_TYPE_PENALTY_THRESHOLD" \
  CLEAN_CANDIDATE_ADAPTIVE_TYPE_PENALTY_WEIGHT="$CANDIDATE_ADAPTIVE_TYPE_PENALTY_WEIGHT" \
  CLEAN_CANDIDATE_ADAPTIVE_TYPE_PENALTY_MAX="$CANDIDATE_ADAPTIVE_TYPE_PENALTY_MAX" \
  CLEAN_CANDIDATE_ADAPTIVE_TYPE_PENALTY_REASONS="$CANDIDATE_ADAPTIVE_TYPE_PENALTY_REASONS" \
  CLEAN_CANDIDATE_DYNAMIC_PROGRESS_TYPE_ANCHOR="$CANDIDATE_DYNAMIC_PROGRESS_TYPE_ANCHOR" \
  CLEAN_CANDIDATE_DYNAMIC_PROGRESS_TYPE_MIN_DELTA="$CANDIDATE_DYNAMIC_PROGRESS_TYPE_MIN_DELTA" \
  CLEAN_CANDIDATE_DYNAMIC_PROGRESS_TYPE_MIN_DELTA_FLOOR="$CANDIDATE_DYNAMIC_PROGRESS_TYPE_MIN_DELTA_FLOOR" \
  CLEAN_CANDIDATE_DYNAMIC_PROGRESS_TYPE_MIN_ROOT_RATIO="$CANDIDATE_DYNAMIC_PROGRESS_TYPE_MIN_ROOT_RATIO" \
  CLEAN_CANDIDATE_DYNAMIC_PROGRESS_TYPE_BONUS_BASE="$CANDIDATE_DYNAMIC_PROGRESS_TYPE_BONUS_BASE" \
  CLEAN_CANDIDATE_DYNAMIC_PROGRESS_TYPE_BONUS_WEIGHT="$CANDIDATE_DYNAMIC_PROGRESS_TYPE_BONUS_WEIGHT" \
  CLEAN_CANDIDATE_DYNAMIC_PROGRESS_TYPE_BONUS_MAX="$CANDIDATE_DYNAMIC_PROGRESS_TYPE_BONUS_MAX" \
  CLEAN_CANDIDATE_STATIC_PROGRESS_TYPE_BONUS="$CANDIDATE_STATIC_PROGRESS_TYPE_BONUS" \
  CLEAN_SECONDARY_VALUE_MODEL="$CLEAN_SECONDARY_VALUE_MODEL" \
  nohup bash "$PIPELINE_DIR/run_postv12_solvedbiased_hybrid_after_wait.sh" \
  > "$HYBRID_LAUNCH_LOG" 2>&1 < /dev/null &
HYBRID_PID=$!

echo "$SCOUT_PID" > "outputs/${POSTRUN_TAG}.scout.pid"
echo "$HYBRID_PID" > "outputs/${POSTRUN_TAG}.hybrid.pid"
log "launched scout pid=${SCOUT_PID}; hybrid pid=${HYBRID_PID}"
